# Generated by Django 4.2.30 on 2026-08-13 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "usuarios",
            "0002_user_azure_object_id_alter_rolepermission_permission_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usuarios.rol"
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="azure_object_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="roles",
        ),
        migrations.RemoveField(
            model_name="user",
            name="telefono",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="azure_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="apellidos",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="nombres",
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="RolePermission",
        ),
        migrations.AddField(
            model_name="userrol",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipo",
            name="asignador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipos_asignador",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipo",
            name="asistente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipos_asistente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrol",
            unique_together={("usuario", "rol")},
        ),
        migrations.AlterUniqueTogether(
            name="equipo",
            unique_together={("asignador", "asistente")},
        ),
    ]
