# Generated by Django 4.2.30 on 2026-08-14 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_equipo_rol_userrol_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="equipo",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="equipo",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="equipo",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipo",
            name="lider",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipos_liderados",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipo",
            name="nombre",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userrol",
            name="rol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios",
                to="usuarios.rol",
            ),
        ),
        migrations.RemoveField(
            model_name="equipo",
            name="asignador",
        ),
        migrations.RemoveField(
            model_name="equipo",
            name="asistente",
        ),
        migrations.CreateModel(
            name="EquipoMiembro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miembros",
                        to="usuarios.equipo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("equipo", "usuario")},
            },
        ),
    ]
