# Generated by Django 4.2.30 on 2026-08-14 17:03

from django.db import migrations
import usuarios.managers


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_alter_equipo_unique_together_equipo_activo_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", usuarios.managers.UserManager()),
            ],
        ),
    ]
