# Generated by Django 4.2.30 on 2026-08-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_rol_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipomiembro',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('INDISPONIBLE', 'Indisponible')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='equipomiembro',
            name='fecha_fin_indisponibilidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipomiembro',
            name='fecha_inicio_indisponibilidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipomiembro',
            name='motivo_indisponibilidad',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipomiembro',
            name='rol_en_equipo',
            field=models.CharField(choices=[('MIEMBRO', 'Miembro'), ('SUB_LIDER', 'Sub-líder')], default='MIEMBRO', max_length=20),
        ),
    ]
