# Generated by Django 4.2.30 on 2026-08-28 06:57

from django.db import migrations, models


def crear_miembro_lider(apps, schema_editor):
    Equipo = apps.get_model('usuarios', 'Equipo')
    EquipoMiembro = apps.get_model('usuarios', 'EquipoMiembro')
    for equipo in Equipo.objects.all():
        if not EquipoMiembro.objects.filter(equipo=equipo, usuario_id=equipo.lider_id).exists():
            EquipoMiembro.objects.create(
                equipo=equipo,
                usuario_id=equipo.lider_id,
                rol_en_equipo='LIDER',
                estado='ACTIVO',
            )
        else:
            # Si ya existe fila para el lider, asegurar rol LIDER
            EquipoMiembro.objects.filter(equipo=equipo, usuario_id=equipo.lider_id).update(rol_en_equipo='LIDER')


def revertir_miembro_lider(apps, schema_editor):
    EquipoMiembro = apps.get_model('usuarios', 'EquipoMiembro')
    EquipoMiembro.objects.filter(rol_en_equipo='LIDER').update(rol_en_equipo='MIEMBRO')


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_equipo_miembro_rol_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipomiembro',
            name='rol_en_equipo',
            field=models.CharField(choices=[('LIDER', 'Líder'), ('MIEMBRO', 'Miembro'), ('SUB_LIDER', 'Sub-líder')], default='MIEMBRO', max_length=20),
        ),
        migrations.RunPython(crear_miembro_lider, revertir_miembro_lider),
    ]
