# Generated by Django 4.2.30 on 2026-08-30 23:30

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_equipo_miembro_lider'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipomiembro',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['lider'], name='usuarios_eq_lider_i_5b1999_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['activo'], name='usuarios_eq_activo_f2f33c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipomiembro',
            index=models.Index(fields=['equipo', 'estado'], name='usuarios_eq_equipo__a98148_idx'),
        ),
        migrations.AddIndex(
            model_name='equipomiembro',
            index=models.Index(fields=['usuario', 'estado'], name='usuarios_eq_usuario_5f5f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipomiembro',
            index=models.Index(fields=['rol_en_equipo'], name='usuarios_eq_rol_en__ea8e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='userrol',
            index=models.Index(fields=['usuario'], name='usuarios_us_usuario_bc44eb_idx'),
        ),
        migrations.AddIndex(
            model_name='userrol',
            index=models.Index(fields=['rol'], name='usuarios_us_rol_id_3cd341_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipomiembro',
            constraint=models.UniqueConstraint(condition=models.Q(('rol_en_equipo', 'LIDER')), fields=('equipo',), name='unico_lider_por_equipo'),
        ),
        migrations.AddConstraint(
            model_name='equipomiembro',
            constraint=models.CheckConstraint(check=models.Q(('fecha_inicio_indisponibilidad__lte', models.F('fecha_fin_indisponibilidad')), ('fecha_inicio_indisponibilidad__isnull', True), ('fecha_fin_indisponibilidad__isnull', True), _connector='OR'), name='chk_fechas_indisponibilidad'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='rol_nombre_unique_lower'),
        ),
    ]
