# Generated by Django 4.2.30 on 2026-08-30 23:48

from django.db import migrations


def forwards_sync_is_active(apps, schema_editor):
    User = apps.get_model("usuarios", "User")
    # Copiar activo -> is_active antes de borrar columna
    for user in User.objects.all():
        try:
            # getattr con default por si columna ya no existe en estado futuro
            activo = getattr(user, "activo", None)
            if activo is not None and activo != user.is_active:
                user.is_active = activo
                user.save(update_fields=["is_active"])
        except Exception:
            continue


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_consolidar_4_roles'),
    ]

    operations = [
        migrations.RunPython(forwards_sync_is_active, backwards_noop),
        migrations.RemoveField(
            model_name='user',
            name='activo',
        ),
    ]
