# Generated by Django 4.2.30 on 2026-08-31 02:40

from django.db import migrations, models
import random
from django.utils import timezone


def generar_codigos(apps, schema_editor):
    User = apps.get_model("usuarios", "User")
    for user in User.objects.filter(codigo__isnull=True):
        base_date = user.fecha_creacion if user.fecha_creacion else timezone.now()
        try:
            prefix = f"MFS-{base_date.strftime('%Y%m%d')}"
        except Exception:
            prefix = f"MFS-{timezone.now().strftime('%Y%m%d')}"
        for _ in range(5):
            candidate = f"{prefix}-{random.randint(10000, 99999)}"
            if not User.objects.filter(codigo=candidate).exists():
                user.codigo = candidate
                user.save(update_fields=["codigo"])
                break
        if not user.codigo:
            import uuid
            user.codigo = f"MFS-{uuid.uuid4().hex[:5].upper()}"
            user.save(update_fields=["codigo"])


def revertir(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_remove_user_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(generar_codigos, revertir),
    ]
