# Generated by Django 4.2.30 on 2026-09-22 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_seed_clientes_ejemplo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibir_correos', models.BooleanField(default=True)),
                ('cliente_solicitud_creada', models.BooleanField(default=True)),
                ('cliente_solicitud_resuelta', models.BooleanField(default=True)),
                ('cliente_solicitud_standby', models.BooleanField(default=True)),
                ('cliente_solicitud_solucionada', models.BooleanField(default=True)),
                ('equipo_nueva_solicitud', models.BooleanField(default=True)),
                ('equipo_pendiente_revision', models.BooleanField(default=True)),
                ('equipo_alerta_diaria', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de notificación',
                'verbose_name_plural': 'Preferencias de notificación',
            },
        ),
    ]
