# Generated by Django 4.2.30 on 2026-09-22 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_preferencianotificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencianotificacion',
            name='equipo_hora_alerta_diaria',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
