# Generated by Django 4.2.30 on 2026-09-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_rename_rol_equipo_gtr_lider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencianotificacion',
            name='aprobador_nueva_solicitud',
        ),
        migrations.RemoveField(
            model_name='preferencianotificacion',
            name='aprobador_pendiente_revision',
        ),
    ]
