# Generated by Django 4.2.30 on 2026-09-29 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_remove_preferencianotificacion_aprobador_nueva_solicitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoAprobador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_aprobador', models.CharField(choices=[('GERENTE', 'Gerente'), ('SUBGERENTE', 'Subgerente'), ('JEFE', 'Jefe')], max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobadores', to='usuarios.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_como_aprobador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['equipo'], name='usuarios_eq_equipo__8a9f7e_idx'), models.Index(fields=['usuario'], name='usuarios_eq_usuario_77ca3d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='equipoaprobador',
            constraint=models.UniqueConstraint(fields=('equipo', 'rol_aprobador'), name='unico_aprobador_por_rol'),
        ),
        migrations.AddConstraint(
            model_name='equipoaprobador',
            constraint=models.UniqueConstraint(fields=('equipo', 'usuario'), name='unico_usuario_aprobador_por_equipo'),
        ),
    ]
