# Generated by Django 4.2.30 on 2026-10-02 04:09
# Editada a mano para convertir EquipoAprobador.rol_aprobador (CharField)
# en una ForeignKey a Rol sin perder datos.

from django.db import migrations, models
import django.db.models.deletion


def backfill_aprobador_rol(apps, schema_editor):
    """Copia el rol (texto) de cada aprobador a la nueva FK por nombre."""
    EquipoAprobador = apps.get_model("usuarios", "EquipoAprobador")
    Rol = apps.get_model("usuarios", "Rol")

    for aprobador in EquipoAprobador.objects.all().iterator():
        nombre = getattr(aprobador, "rol_aprobador", None)
        if not nombre:
            continue
        rol = Rol.objects.filter(nombre__iexact=str(nombre)).first()
        if rol is None:
            rol = Rol.objects.create(
                nombre=str(nombre),
                descripcion="Rol de aprobación heredado",
                activo=True,
            )
        aprobador.rol_aprobador_rol_id = rol.pk
        aprobador.save(update_fields=["rol_aprobador_rol"])


def revertir_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_limpiar_aprobadores_invalidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='rol_equipo',
            field=models.ForeignKey(blank=True, help_text='Rol del líder que determina la cadena de aprobación del equipo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='usuarios.rol'),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_liderar',
            field=models.BooleanField(default=False, help_text='Si está activo, los usuarios con este rol pueden ser líderes de un equipo.'),
        ),
        migrations.AddField(
            model_name='rol',
            name='superior',
            field=models.ForeignKey(blank=True, help_text='Rol superior directo que aprueba las solicitudes de este rol. Vacío en el rol raíz de la organización.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subordinados', to='usuarios.rol'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('COLABORADOR', 'Colaborador'), ('CLIENTE', 'Cliente'), ('ADMINISTRADOR', 'Administrador')], db_index=True, default='COLABORADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.CharField(choices=[('GERENTE', 'Equipo de Gerente'), ('SUBGERENTE', 'Equipo de Subgerente'), ('JEFE', 'Equipo de Jefe'), ('GTR', 'Equipo GTR')], db_index=True, default='GTR', help_text='[DEPRECADO] Espejo del nombre del rol del líder. La fuente de verdad es rol_equipo.', max_length=20),
        ),
        # Conversión segura de rol_aprobador (texto) -> FK a Rol.
        migrations.AddField(
            model_name='equipoaprobador',
            name='rol_aprobador_rol',
            field=models.ForeignKey(blank=True, help_text='Rol de la cadena de aprobación que ocupa este usuario en el equipo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos_aprobador', to='usuarios.rol'),
        ),
        migrations.RunPython(backfill_aprobador_rol, revertir_backfill),
        # El constraint único referencia la columna de texto: quitarlo antes de
        # eliminar el campo (SQLite no permite drop de columnas en constraints).
        migrations.RemoveConstraint(
            model_name='equipoaprobador',
            name='unico_aprobador_por_rol',
        ),
        migrations.RemoveField(
            model_name='equipoaprobador',
            name='rol_aprobador',
        ),
        migrations.RenameField(
            model_name='equipoaprobador',
            old_name='rol_aprobador_rol',
            new_name='rol_aprobador',
        ),
        migrations.AlterField(
            model_name='equipoaprobador',
            name='rol_aprobador',
            field=models.ForeignKey(help_text='Rol de la cadena de aprobación que ocupa este usuario en el equipo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos_aprobador', to='usuarios.rol'),
        ),
        migrations.AddConstraint(
            model_name='equipoaprobador',
            constraint=models.UniqueConstraint(fields=('equipo', 'rol_aprobador'), name='unico_aprobador_por_rol'),
        ),
    ]
