# Generated by Django 4.2.30 on 2026-10-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_backfill_tipo_usuario_jerarquia'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipoaprobador',
            name='unico_aprobador_por_rol',
        ),
    ]
