# Generated by Django 4.2.30 on 2026-10-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_eliminar_rol_asistente'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
