# Generated by Django 4.2.30 on 2026-10-02 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_user_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener exactamente 8 números.', regex='^\\d{8}$')]),
        ),
    ]
