# Generated by Django 4.2.30 on 2026-10-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_alter_user_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='auto_aprobar',
            field=models.BooleanField(default=False, help_text='Si está activo, las solicitudes de equipos de este rol saltan la fase de aprobadores y pasan directo a revisión del líder.'),
        ),
        migrations.DeleteModel(
            name='EquipoAprobador',
        ),
    ]
