# Generated by Django 4.2.30 on 2026-10-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_rol_auto_aprobar_delete_equipoaprobador'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descripcion_cargo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
