# Generated by Django 4.2.30 on 2026-08-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('cliente', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_aproximada', models.DateField()),
            ],
        ),
    ]
