# Generated by Django 4.2.30 on 2026-08-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fecha_fin_aproximada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='fecha_solicitud',
            field=models.DateTimeField(),
        ),
    ]
