# Generated by Django 4.2.30 on 2026-08-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_fecha_fin_aproximada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fecha_fin_aproximada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
