# Generated by Django 4.2.30 on 2026-08-14 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usuarios", "0004_alter_equipo_unique_together_equipo_activo_and_more"),
        ("clientes", "0001_initial"),
        ("tasks", "0003_alter_task_fecha_fin_aproximada_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivoTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="tareas/")),
                ("nombre", models.CharField(max_length=255)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "subido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subtarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EN_ESPERA", "En espera"),
                            ("EN_DESARROLLO", "En desarrollo"),
                            ("SOLUCIONADO", "Solucionado"),
                        ],
                        default="EN_ESPERA",
                        max_length=20,
                    ),
                ),
                ("peso", models.PositiveIntegerField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "asignado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subtareas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asunto", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EN_ESPERA", "En espera"),
                            ("APROBADO", "Aprobado"),
                            ("EN_DESARROLLO", "En desarrollo"),
                            ("RECHAZADO", "Rechazado"),
                            ("SOLUCIONADO", "Solucionado"),
                        ],
                        default="EN_ESPERA",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_entrega_aproximada",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("motivo_rechazo", models.TextField(blank=True)),
                (
                    "progreso",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "aprobador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tareas_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tareas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tareas",
                        to="usuarios.equipo",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.AddField(
            model_name="subtarea",
            name="tarea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtareas",
                to="tasks.tarea",
            ),
        ),
        migrations.AddField(
            model_name="archivotarea",
            name="tarea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archivos",
                to="tasks.tarea",
            ),
        ),
    ]
