# Generated by Django 4.2.30 on 2026-08-30 23:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campanas', '0001_initial'),
        ('tasks', '0005_tarea_solicitante_alter_tarea_aprobador'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependenciaSubtarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DependenciaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='subtarea',
            name='fecha_standby',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='motivo_standby',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='standby_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standbys_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='subcampana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='campanas.subcampana'),
        ),
        migrations.AlterField(
            model_name='archivotarea',
            name='subido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtarea',
            name='estado',
            field=models.CharField(choices=[('EN_ESPERA', 'En espera'), ('EN_DESARROLLO', 'En desarrollo'), ('SOLUCIONADO', 'Solucionado'), ('STAND_BY', 'En pausa')], db_index=True, default='EN_ESPERA', max_length=20),
        ),
        migrations.AlterField(
            model_name='subtarea',
            name='peso',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='progreso',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='archivotarea',
            index=models.Index(fields=['tarea'], name='tasks_archi_tarea_i_32aa91_idx'),
        ),
        migrations.AddIndex(
            model_name='subtarea',
            index=models.Index(fields=['tarea', 'estado'], name='tasks_subta_tarea_i_3bb2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='subtarea',
            index=models.Index(fields=['asignado', 'estado'], name='tasks_subta_asignad_5092fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['estado', 'equipo'], name='tasks_tarea_estado_0e8ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['solicitante', 'estado'], name='tasks_tarea_solicit_c40d79_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['cliente', 'estado'], name='tasks_tarea_cliente_d7a8d8_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['fecha_creacion'], name='tasks_tarea_fecha_c_91a2f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='subtarea',
            constraint=models.CheckConstraint(check=models.Q(('peso__gte', 1)), name='chk_subtarea_peso_gte1'),
        ),
        migrations.AddConstraint(
            model_name='subtarea',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('estado', 'STAND_BY'), ('motivo_standby__isnull', False)), models.Q(('estado', 'STAND_BY'), _negated=True), ('motivo_standby', ''), _connector='OR'), name='chk_standby_motivo_lenient'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.CheckConstraint(check=models.Q(('progreso__gte', 0), ('progreso__lte', 100)), name='chk_tarea_progreso_0_100'),
        ),
        migrations.AddField(
            model_name='dependenciatarea',
            name='bloqueada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_origen', to='tasks.tarea'),
        ),
        migrations.AddField(
            model_name='dependenciatarea',
            name='bloqueadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_destino', to='tasks.tarea'),
        ),
        migrations.AddField(
            model_name='dependenciasubtarea',
            name='bloqueada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_origen', to='tasks.subtarea'),
        ),
        migrations.AddField(
            model_name='dependenciasubtarea',
            name='bloqueadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_destino', to='tasks.subtarea'),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='dependencias',
            field=models.ManyToManyField(blank=True, related_name='bloqueadas', through='tasks.DependenciaSubtarea', to='tasks.subtarea'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='dependencias',
            field=models.ManyToManyField(blank=True, related_name='tareas_bloqueadas', through='tasks.DependenciaTarea', to='tasks.tarea'),
        ),
        migrations.AddConstraint(
            model_name='dependenciatarea',
            constraint=models.CheckConstraint(check=models.Q(('bloqueada', models.F('bloqueadora')), _negated=True), name='chk_dep_tarea_no_self'),
        ),
        migrations.AlterUniqueTogether(
            name='dependenciatarea',
            unique_together={('bloqueada', 'bloqueadora')},
        ),
        migrations.AddConstraint(
            model_name='dependenciasubtarea',
            constraint=models.CheckConstraint(check=models.Q(('bloqueada', models.F('bloqueadora')), _negated=True), name='chk_dep_no_self'),
        ),
        migrations.AlterUniqueTogether(
            name='dependenciasubtarea',
            unique_together={('bloqueada', 'bloqueadora')},
        ),
    ]
