# Generated by Django 4.2.30 on 2026-08-31 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_dependenciasubtarea_dependenciatarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_standby',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='motivo_standby',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='standby_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_standby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('EN_ESPERA', 'En espera'), ('APROBADO', 'Aprobado'), ('EN_DESARROLLO', 'En desarrollo'), ('RECHAZADO', 'Rechazado'), ('SOLUCIONADO', 'Solucionado'), ('STAND_BY', 'En pausa')], default='EN_ESPERA', max_length=20),
        ),
    ]
