# Generated by Django 4.2.30 on 2026-08-31 02:15

from django.db import migrations, models
import random
from django.utils import timezone


def generar_tickets(apps, schema_editor):
    Tarea = apps.get_model("tasks", "Tarea")
    for tarea in Tarea.objects.filter(ticket__isnull=True):
        # generar ticket basado en fecha y id
        try:
            base = tarea.fecha_creacion.strftime("%Y%m%d") if tarea.fecha_creacion else timezone.now().strftime("%Y%m%d")
        except Exception:
            base = timezone.now().strftime("%Y%m%d")
        for _ in range(5):
            candidate = f"TCK-{base}-{random.randint(1000,9999)}"
            if not Tarea.objects.filter(ticket=candidate).exists():
                tarea.ticket = candidate
                tarea.save(update_fields=["ticket"])
                break
        if not tarea.ticket:
            tarea.ticket = f"TCK-{tarea.id:06d}"
            tarea.save(update_fields=["ticket"])


def revertir(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tarea_fecha_standby_tarea_motivo_standby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_solucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='ticket',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(generar_tickets, revertir),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['ticket'], name='tasks_tarea_ticket_4e91bf_idx'),
        ),
    ]
