# Generated by Django 4.2.30 on 2026-08-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_tarea_fecha_solucion_tarea_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tarea',
            name='tasks_tarea_cliente_d7a8d8_idx',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='cliente',
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['subcampana', 'estado'], name='tasks_tarea_subcamp_2ee607_idx'),
        ),
    ]
