# Generated by Django 4.2.30 on 2026-09-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_tarea_tasks_tarea_cliente_d7a8d8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtarea',
            name='fecha_fin_standby',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_fin_standby',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
