# Generated by Django 4.2.30 on 2026-09-03 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0010_subtarea_fecha_fin_standby_tarea_fecha_fin_standby'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CREACION', 'Creación'), ('INICIO', 'Inicio'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('STANDBY_INICIO', 'Inicio de standby'), ('STANDBY_FIN', 'Fin de standby'), ('FIN', 'Fin'), ('CAMBIO_ASIGNADO', 'Cambio de asignado'), ('CAMBIO_PROGRESO', 'Cambio de progreso')], max_length=30)),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detalle', models.TextField(blank=True)),
                ('subtarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.subtarea')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.tarea')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarea_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['tarea', 'fecha'], name='tasks_tarea_tarea_i_533e1b_idx'), models.Index(fields=['subtarea', 'fecha'], name='tasks_tarea_subtare_c3e98b_idx'), models.Index(fields=['tipo_evento', 'fecha'], name='tasks_tarea_tipo_ev_72ea40_idx')],
            },
        ),
    ]
