# Generated by Django 4.2.30 on 2026-09-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_tarealog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='incluye_sabado',
            field=models.BooleanField(default=False, help_text='Si está activo, el contador incluye sábados de 9am a 1pm; si no, solo L-V 9-18.'),
        ),
    ]
