# Generated by Django 4.2.30 on 2026-09-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_subtarea_activo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subtarea',
            new_name='tasks_subta_tarea_i_a021cf_idx',
            old_name='tasks_subta_tarea_i_57a7f8_idx',
        ),
        migrations.RenameIndex(
            model_name='subtarea',
            new_name='tasks_subta_activo_5622dd_idx',
            old_name='tasks_subta_activo_2a14d1_idx',
        ),
    ]
