# Generated by Django 4.2.30 on 2026-09-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_formato_ids_secuencial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subtarea',
            new_name='tasks_subta_codigo_e84e2e_idx',
            old_name='tasks_subta_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='tarea',
            new_name='tasks_tarea_activo_0bce92_idx',
            old_name='tasks_tarea_activo_idx',
        ),
    ]
