# Generated by Django 4.2.30 on 2026-09-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_paso_aprobacion_lider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobaciontarea',
            name='nivel',
            field=models.CharField(choices=[('GERENTE', 'Gerente'), ('SUBGERENTE', 'Subgerente'), ('SUPERVISOR', 'Supervisor'), ('LIDER', 'Líder'), ('COMPLETADO', 'Completado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='paso_aprobacion',
            field=models.CharField(choices=[('GERENTE', 'Gerente'), ('SUBGERENTE', 'Subgerente'), ('SUPERVISOR', 'Supervisor'), ('LIDER', 'Líder'), ('COMPLETADO', 'Completado')], db_index=True, default='GERENTE', help_text='Nivel de la cadena de aprobación que debe resolver la solicitud.', max_length=20),
        ),
    ]
