# Generated by Django 4.2.30 on 2026-09-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_jerarquia_jefe_gtr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AprobacionTarea',
        ),
        migrations.RemoveIndex(
            model_name='tarea',
            name='tasks_tarea_paso_estado_idx',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='aprobador',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='paso_aprobacion',
        ),
    ]
