# Generated by Django 4.2.30 on 2026-09-29 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0024_remove_aprobaciontarea_tarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='paso_aprobacion',
            field=models.CharField(choices=[('APROBADORES', 'Aprobadores'), ('LIDER', 'Revisión del líder'), ('COMPLETADO', 'Completado')], db_index=True, default='APROBADORES', help_text='Fase de aprobación que debe resolverse: aprobadores del equipo o su líder.', max_length=20),
        ),
        migrations.CreateModel(
            name='AprobacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('APROBADORES', 'Aprobadores'), ('LIDER', 'Revisión del líder'), ('COMPLETADO', 'Completado')], max_length=20)),
                ('accion', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='tasks.tarea')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha', 'id'],
                'indexes': [models.Index(fields=['tarea', 'fecha'], name='tasks_aprob_tarea_i_04bcd4_idx'), models.Index(fields=['nivel'], name='tasks_aprob_nivel_885d9a_idx')],
            },
        ),
    ]
