# Generated by Django 4.2.30 on 2026-08-30 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanas', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='SubCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=40, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcampanas', to='campanas.campana')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_otorgado', models.DateTimeField(auto_now_add=True)),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='campanas.campana')),
                ('subcampana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='campanas.subcampana')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_campana', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='subcampana',
            index=models.Index(fields=['campana', 'activo'], name='campanas_su_campana_0dee89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcampana',
            unique_together={('campana', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='permisocampana',
            index=models.Index(fields=['usuario'], name='campanas_pe_usuario_8a7774_idx'),
        ),
        migrations.AddConstraint(
            model_name='permisocampana',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('campana__isnull', False), ('subcampana__isnull', True)), models.Q(('campana__isnull', True), ('subcampana__isnull', False)), _connector='OR'), name='chk_permiso_xor'),
        ),
        migrations.AddConstraint(
            model_name='permisocampana',
            constraint=models.UniqueConstraint(condition=models.Q(('campana__isnull', False)), fields=('usuario', 'campana'), name='uniq_permiso_usuario_campana'),
        ),
        migrations.AddConstraint(
            model_name='permisocampana',
            constraint=models.UniqueConstraint(condition=models.Q(('subcampana__isnull', False)), fields=('usuario', 'subcampana'), name='uniq_permiso_usuario_subcampana'),
        ),
        migrations.AddIndex(
            model_name='campana',
            index=models.Index(fields=['cliente', 'activo'], name='campanas_ca_cliente_010b89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campana',
            unique_together={('cliente', 'nombre')},
        ),
    ]
