# Generated by Django 4.2.30 on 2026-08-31 04:40

from django.db import migrations, models


def _copiar_cliente_a_campana(apps, schema_editor):
    Campana = apps.get_model("campanas", "Campana")
    for camp in Campana.objects.select_related("cliente").all():
        try:
            cliente = camp.cliente
            if cliente:
                camp.razon_social = cliente.razon_social or ""
                camp.ruc = cliente.ruc
                camp.correo = cliente.correo or ""
                camp.telefono = cliente.telefono or ""
                camp.direccion = cliente.direccion or ""
                camp.save(update_fields=["razon_social", "ruc", "correo", "telefono", "direccion"])
        except Exception:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0003_seed_csc_full'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campana',
            name='campanas_ca_cliente_010b89_idx',
        ),
        migrations.AlterUniqueTogether(
            name='campana',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='campana',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='campana',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campana',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='campana',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='campana',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='campana',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='campana',
            index=models.Index(fields=['activo'], name='campanas_ca_activo_499315_idx'),
        ),
        migrations.RunPython(_copiar_cliente_a_campana, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='campana',
            name='cliente',
        ),
    ]
