services:
  backend:
    build:
      context: ./BACKEND/mfbackend
      dockerfile: Dockerfile

    container_name: mf-backend

    working_dir: /app

    command: python manage.py runserver 0.0.0.0:8000

    environment:
      AZURE_TENANT_ID: 8d669035-9c23-4bfe-8439-816c8408e589
      AZURE_CLIENT_ID: 10a3c5ce-2a51-456e-8bc2-6256f4720848
      AZURE_ALLOWED_DOMAINS: ""

    volumes:
      - ./BACKEND/mfbackend:/app

    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./FRONTEND/mffrontend/my-app
      dockerfile: Dockerfile

    container_name: mf-frontend

    working_dir: /app

    command: npm run dev

    volumes:
      - ./FRONTEND/mffrontend/my-app:/app
      - /app/node_modules

    ports:
      - "3000:3000"

    environment:
      HOSTNAME: 0.0.0.0

    depends_on:
      - backend